language: node_js
node_js:
  - 0.12
  - 4
  - 6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  - CXX=g++-6
script:
  - if npm run travis-coverage-$TRAVIS_NODE_VERSION >& build.log; then
      tail -n 100 build.log;
    else
      r=$?
      tail -n 1000 build.log;
      exit $?
    fi
