environment:
  matrix:
    - nodejs_version: "10.13.0"
    - nodejs_version: "11.1.0"

install:
#  - ps: Install-Product node $env:nodejs_version
  - ps: Update-NodeJsInstallation $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test-win

build: off
