environment:
  matrix:
    - nodejs_version: "11.4.0"

install:
#  - ps: Install-Product node $env:nodejs_version
  - ps: Update-NodeJsInstallation $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test-win

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
