environment:
  POSTGRES_PATH: C:\Program Files\PostgreSQL\10
  PGUSER: postgres
  PGPASSWORD: Password12!
  NODE_CONFIG: '{"db":"postgresql://postgres:Password12!@localhost/qlobber-pg"}'
  NODE_OPTIONS: --max-http-header-size=32768
  matrix:
    - nodejs_version: "12.6.0"

init:
  - set PATH=%POSTGRES_PATH%\bin;%PATH%

services:
  -postgresql101

install:
#  - ps: Update-NodeJsInstallation $env:nodejs_version x64
  - ps: Remove-NodeJsInstallation $(Get-InstalledNodeJsVersion).version $(Get-InstalledNodeJsVersion).bitness
  - ps: cmd /c start /wait msiexec /i $(Get-NodeJsInstallPackage $env:nodejs_version x64) /q
  - node --version
  - npm --version
  - npm install

build:
  - createdb qlobber-pg
  - npm run migrate up

test_script:
  - npm run test-win

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
