version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-15
      - test-14
      - test-12
jobs:
  test-15: &test-template
    docker:
      - &node-template
        image: cimg/node:15.2.0
        environment:
          NODE_OPTIONS: --max-http-header-size=32768
          NODE_CONFIG: '{"db":"postgresql://postgres@localhost/qlobber-pg"}'
      - &pg-template
        image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: qlobber-pg
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt update
            sudo apt -y install libboost-context-dev lcov python2
            npm install
      - run:
          name: test
          command: ./test/ci-test.sh
          environment:
            CHECK_VER: 15
  test-14:
    <<: *test-template
    docker:
      - <<: *node-template
        image: cimg/node:14.15.0
      - *pg-template
  test-12:
    <<: *test-template
    docker:
      - <<: *node-template
        image: cimg/node:12.19.0
      - *pg-template
