version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-13
      - test-12
jobs:
  test-13: &test-template
    docker:
      - &node-template
        image: circleci/node:13.5.0-buster
        environment:
          CXX: g++-9
          NODE_OPTIONS: --max-http-header-size=32768
          NODE_CONFIG: '{"db":"postgresql://postgres@localhost/qlobber-pg"}'
      - &pg-template
        image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: qlobber-pg
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt update
            sudo apt -y install libboost1.70-dev g++-9 lcov
            npm install
      - run:
          name: test
          command: ./test/ci-test.sh
  test-12:
    <<: *test-template
    docker:
      - <<: *node-template
        image: circleci/node:12.14.0-buster
      - *pg-template
