version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-13
      - test-12
jobs:
  test-13: &test-template
    docker:
      - image: circleci/node:13.5.0
        environment:
          CXX: g++-6
          NODE_OPTIONS: --max-http-header-size=32768
          NODE_CONFIG: '{"db":"postgresql://postgres@localhost/qlobber-pg"}'
      - image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: qlobber-pg
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo bash -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
            sudo apt-get -y update
            sudo apt-get -y install -t unstable g++-6 lcov
            npm install
      - run:
          name: test
          command: ./test/ci-test.sh
  test-12:
    <<: *test-template
    docker:
      - image: circleci/node:12.14.0
