name: ci

on: [push, pull_request]

jobs:
    test:
        strategy:
            matrix:
                node-version: [12, 14]
                platform: [ubuntu, windows]

        runs-on: ${{ matrix.platform }}-latest

    services:
        postgres:
            image: postgres
            env:
                POSTGRES_USER: postgres
                POSTGRES_DB: qlobber-pg
                POSTGRES_HOST_AUTH_METHOD: trust
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 5432:5432

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2.1.0
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install
          run: npm ci

        - name: Run tests
          run: ./test/ci-test.sh
          env:
            CHECK_VER: 14
